services:
  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: "dwh-staging"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - dbdwh:/data/postgres-dwh-aht
    ports:
      - "4004:5432"
    restart: unless-stopped
volumes:
  dbdwh:
    external: true
